version: '3.8'

services:
  # --- DB1 (Master 1) ---
  db1:
    image: mysql:8.0
    container_name: evservice_db1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evservicedb
      MYSQL_USER: EVServiceDb
      MYSQL_PASSWORD: 123456
    volumes:
      - db1_data:/var/lib/mysql
    networks:
      - ev_network
    command:
      --default-authentication-plugin=mysql_native_password
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-slave-updates=ON
      --auto-increment-increment=2
      --auto-increment-offset=1
      --bind-address=0.0.0.0
    restart: unless-stopped

  # --- DB2 (Master 2) ---
  db2:
    image: mysql:8.0
    container_name: evservice_db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: evservicedb
      MYSQL_USER: EVServiceDb
      MYSQL_PASSWORD: 123456
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      - ev_network
    command:
      --default-authentication-plugin=mysql_native_password
      --server-id=2
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --log-slave-updates=ON
      --auto-increment-increment=2
      --auto-increment-offset=2
      --bind-address=0.0.0.0
    restart: unless-stopped

  # --- HAProxy (Load Balancer) ---
  haproxy:
    image: haproxy:latest
    container_name: evservice_haproxy
    ports:
      - "3307:3306" # Cổng kết nối từ máy thật
      - "8404:8404"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - db1
      - db2
    networks:
      - ev_network
    restart: unless-stopped

  # --- Backend ---
  backend:
    build: ./EVService
    container_name: evservice_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Kết nối vào haproxy
      SPRING_DATASOURCE_URL: jdbc:mysql://haproxy:3306/evservicedb?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: EVServiceDb
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - haproxy
    networks:
      - ev_network

  # --- Frontend ---
  frontend:
    build: ./EVService-FE-Ts
    container_name: evservice_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - ev_network

volumes:
  db1_data:
  db2_data:

networks:
  ev_network:
    driver: bridge